### ISSUE TITLE
JsonSyntaxException for getWorkflow

### ISSUE THREAD

**Issue by chengchaoyin** [argoproj-labs/argo-client-java#1]
argo version:2.5.2
k8s:V1.13.1
language:java
Class:WorkflowServiceApi,method:getWorkflow
I had trouble using WorkflowServiceApi to get Workflow info,a error has occurred:
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 501 path $.spec.templates[0].steps[0]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 22 more
Looking forward to your reply soon!

**Comment by mac9416** [comment]
Similar: `Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 697 path $.items[0].spec.templates[0]`.

Argo built from 20d6e27bdf11389f23b2efe1be4ef737f333221d. I'm going to try again with 2.6.1.

**Comment by mac9416** [comment]
Ended up back at 2.5.2 since that was the version released about the same time as the client. Same error.

**Comment by mac9416** [comment]
Looks like this is getting serialized (by Argo server) simply as an array, while Swagger believes it should be an object of the shape `{ "steps": [] }`.

```golang
type ParallelSteps struct {
	Steps []WorkflowStep `protobuf:"bytes,1,rep,name=steps"`
}
```

**Comment by mac9416** [comment]
@alexec looks like this got auto-closed. But we'll still need to regenerate and push this repo, right?

**Comment by paravatha** [comment]
I am seeing the same error 
`Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 47868 path $.items[10].spec.templates[0].steps[0]`

Any idea how to fix this?

**Comment by mac9416** [comment]
@paravatha the underlying issue in the argo repo has been fixed, but this code hasn't been regenerated.

I'd recommend using argo-client-gen to generate a client for your specific Argo version, if it's a recent version. If not, you may have to backport the fix.

**Comment by paravatha** [comment]
@mac9416 , I am able to build and use the generated client jar
One more thing I noticed is I had to rollback  
from 
**io.kubernetes:client-java-api:8.0.0**
to
**io.kubernetes:client-java-api:5.0.0**

**Comment by mac9416** [comment]
@paravatha interesting. Do you know why the rollback was necessary, or was it just trial-and-error?

**Comment by paravatha** [comment]
It seems like the package structure was changed after 5..0.0
**io.kubernetes.client.models**

![image](https://user-images.githubusercontent.com/8755869/87215985-ece3f480-c300-11ea-8e82-6e3ffb7a2485.png)

to 
**io.kubernetes.client.openapi.models**

![image](https://user-images.githubusercontent.com/8755869/87216013-26b4fb00-c301-11ea-8dc7-9fe0a6edffea.png)

**Comment by paravatha** [comment]
Here you go
https://github.com/kubernetes-client/java/blob/master/CHANGELOG.md#700

_Move/rename generated OpenAPI packages (including apis, models..) from io.kubernetes.client to io.kubernetes.client.openapi for OSGi integration. (#737)_
